[package]
name = "keyboard_layout"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
name = "common"
path = "./src/lib/common.rs"

[dependencies]
walkdir = "2"
triple_arena = "0.12"
rand_xoshiro = { version = "0.6", default-features = false }
smallvec = "1.11"
awint = "0.13"
